site_name: Python Template
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
extra:
  generator: false