# untested

[project]
name = "mypackage"
version = "0.0.1"
dynamic = ["dependencies"]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.ruff]
line-length = 100  # defaults to 88
