FROM python:3.12
ENV DOCKER_WORKDIR="/app"
WORKDIR $DOCKER_WORKDIR
COPY pyproject.toml ./
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --with cloud
COPY . /app

EXPOSE 8080
CMD ["python", "./src/docker_entry.py"]